config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chat_rooms, only: [ :show ] do
    resources :messages, only: [ :create ]
  end

  mount ActionCable.server => "/cable"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  after_create :broadcast_message

  belongs_to :chat_room
  belongs_to :user
  validates :content, presence: true, allow_blank: false

  def from?(some_user)
    user == some_user
  end

  def broadcast_message
    ActionCable.server.broadcast("chat_room_#{chat_room.id}", {
      message_partial: ApplicationController.renderer.render(partial: "messages/message", locals: { message: self, user_is_messages_author: false }),
      current_user_id: user.id
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy]

  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
    @chat_room = ChatRoom.includes(messages: :user).find(params[:id])
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = ChatRoom.new(chat_room_params)

    respond_to do |format|
      if @chat_room.save
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.fetch(:chat_room, {})
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(message_params)
    @chat_room = ChatRoom.find(params[:chat_room_id])
    @message.chat_room = @chat_room
    @message.user = current_user
    if @message.save
      respond_to do |format|
        format.html { redirect_to chat_room_path(@chat_room) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render "chat_rooms/show" }
        format.js
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_form.html.erb
<%= simple_form_for(@chat_room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chat_rooms.each do |chat_room| %>
      <tr>
        <td><%= link_to 'Show', chat_room %></td>
        <td><%= link_to 'Edit', edit_chat_room_path(chat_room) %></td>
        <td><%= link_to 'Destroy', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Room', new_chat_room_path %>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="chat-header"><h4>#<%= @chat_room.name %></h4></div>
      <div class="messages">
        <% @chat_room.messages.each do |message| %>
          <%= render "messages/message", message: message, user_is_messages_author: message.user == current_user %>
        <% end %>
      </div>
      <div id="create-message">
        <%= simple_form_for [ @chat_room, Message.new ], remote: true, html: {autocomplete: "off" } do |f| %>
          <%= f.input :content, label: false %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['chat_room_<%= @chat_room.id %>'] = App.cable.subscriptions.create({ channel: 'ChatRoomsChannel', chat_room_id: <%= @chat_room.id %> }, {
      received: (data) => {
        console.log('data', data)
        if (data.current_user_id !== <%= current_user.id %>) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
          scrollLastMessageIntoView();
        }
      }
    })
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>YNWA - You Will Never Walk Alone</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message <%= user_is_messages_author ? "right" : "" %>">
  <%= image_tag message.user.avatar_url, class: "avatar" %>
  <div class="message-content"><%= message.content %></div>
</div>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
  // handle validation errors later
<% else %>
  const messagesContainer = document.querySelector('.messages');
  messagesContainer.insertAdjacentHTML('beforeend', '<%= j render "message", message: @message, user_is_messages_author: true %>');
  const input = document.querySelector('#message_content');
  input.value = '';
  input.blur();
  scrollLastMessageIntoView();
<% end %>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>
<div class="container">
  <div class="row">
    <div class="banner">
      <div class="banner-content text-center">
        <h1>YNWA: You will never walk alone!</h1>
        <p>YNWA permet aux entraîneurs et éducateurs de s'organiser, s'entraider et blablabla</p>
        <%= link_to "Droit au but !", new_user_session_path, class: "btn btn-lg btn-primary"  %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-6">
          <div class="card"></div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-6">
          <div class="card"></div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-6">
          <div class="card"></div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <% if user_signed_in? %>
        <div class="dropdown">
          <%= image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>